services:
  cirqlex_app:
    build: .
    container_name: cirqlex_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./alembic:/app/alembic  # Volume for Alembic
  db:
    image: postgres:latest
    container_name: cirqlex_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cirqlex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: